### PR TITLE
Add youtube integration

### PR DESCRIPTION
**Pull request by larryworm1127**
- Added Google OAuth that automatically creates a User and Influencer object if the User associated with the Google ID doesn't exist, otherwise simply log user in.
- Removed the original influencer register and login views and updated urls such that it no longer identify between influencer or company
- Moved a few react components and utility functions around for clarity
- Updated User and Influencer to add new fields.
- Updated unittests for auth based on new endpoints changes

### CODE REVIEW

**Review by zekai128 — COMMENTED** [review]
Do we need a test for the one step register-login flow?

**Review by matticyang — COMMENTED** [review]
Do we need more tests, otherwise looks good

**Comment by larryworm1127** [comment]
We can't really add test for oauth since we would need a Google account specifically for test.

**Review by zekai128 — APPROVED** [review]
looks good

**Pull request merged**
